name: AppLabelMysql

services:

  microlabelfront:
    #image: $FRONT_DOCKER_IMAGE
    build: # Build locally
      context: ./front-end
    ports:
      - "8887:80"

  # BACKEND SERVER MACHINE NAME
  microlabelback:
    image: $BACKEND_DOCKER_IMAGE # Get from internet
    #build: # build locally
    #  context: ./back-end # Building Docker file from '.' the current repository
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "$APP_PORT:$APP_PORT"
    networks:
      - mysql-private-tunnel
    environment:
      APP_PORT: $APP_PORT
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD 
      DB_NAME: $DB_NAME
      DB_HOSTNAME: $DB_HOSTNAME
      
  # N'exposé mongo que quand vous etes en devellopement
  # MONGODB MACHINE NAME
  mysql:
    image: mysql
    restart: always
    #ports:
    #  - 3306:3306
    #expose:
    #  - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--connect-timeout", "4"]
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - mysql-private-tunnel
    environment:
      #HOSTNAME: db.mysql.local
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD 
      MYSQL_DATABASE: $DB_NAME
      MYSQL_INITDB_SKIP_TZINFO: yes

networks:
  mysql-private-tunnel: