name: backend-production

services:

  # BACKEND SERVER MACHINE NAME
  microlabelback:
    #image: maissacrement/benomads-appmanager-back:0.0.1 # Get from internet
    build: # build locally
      context: . # Building Docker file from '.' the current repository
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "$APP_PORT:$APP_PORT"
    networks:
      - mysql-private-tunnel
    environment:
      APP_PORT: $APP_PORT
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD 
      DB_NAME: $DB_NAME
      DB_HOSTNAME: $DB_HOSTNAME
      
  # N'exposé mongo que quand vous etes en devellopement
  # MONGODB MACHINE NAME
  mysql:
    image: mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    #expose:
    #  - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--connect-timeout", "4"]
      interval: 5s
      timeout: 5s
      retries: 55
    #networks:
    #  - mysql-private-tunnel
    environment:
      #HOSTNAME: db.mysql.local
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD 
      MYSQL_DATABASE: $DB_NAME
      MYSQL_INITDB_SKIP_TZINFO: yes


networks:
  mysql-private-tunnel: