name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image for AppLabelMysql Front
      run: docker build -t maissacrement/benomads-applabel:mysql-react-front ./front-end
    
    - name: Build the Docker image for AppLabelMysql Backend
      run: docker build -t maissacrement/benomads-applabel:mysql-react-back ./back-end
